default_agent: github_assistant
agents:
  github_assistant:
    name: github_assistant
    entrypoint: /Users/yukimatsuyoshi/private/repo/agentcore_handson/github-assistant/agent.py
    deployment_type: direct_code_deploy
    runtime_type: PYTHON_3_12
    platform: linux/arm64
    container_runtime: null
    source_path: /Users/yukimatsuyoshi/private/repo/agentcore_handson/github-assistant
    aws:
      execution_role: arn:aws:iam::605664253368:role/AmazonBedrockAgentCoreSDKRuntime-us-west-2-578754c540
      execution_role_auto_create: false
      account: '605664253368'
      region: us-west-2
      ecr_repository: null
      ecr_auto_create: false
      s3_path: s3://bedrock-agentcore-codebuild-sources-605664253368-us-west-2
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: github_assistant-ntcq55DsH7
      agent_arn: arn:aws:bedrock-agentcore:us-west-2:605664253368:runtime/github_assistant-ntcq55DsH7
      agent_session_id: 239554bc-e79e-4187-8b9f-d8e708caeec5
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    memory:
      mode: NO_MEMORY
      memory_id: null
      memory_arn: null
      memory_name: null
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
