default_agent: gitHub_slack_assistant
agents:
  gitHub_slack_assistant:
    name: gitHub_slack_assistant
    entrypoint: /Users/yukimatsuyoshi/private/repo/agentcore_handson/github-assistant/agent.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: none
    source_path: /Users/yukimatsuyoshi/private/repo/agentcore_handson/github-assistant
    aws:
      execution_role: arn:aws:iam::605664253368:role/AmazonBedrockAgentCoreSDKRuntime-us-west-2-97912bf415
      execution_role_auto_create: false
      account: "605664253368"
      region: us-west-2
      ecr_repository: 605664253368.dkr.ecr.us-west-2.amazonaws.com/bedrock-agentcore-github_slack_assistant
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: gitHub_slack_assistant-TUpC4S6NOh
      agent_arn: arn:aws:bedrock-agentcore:us-west-2:605664253368:runtime/gitHub_slack_assistant-TUpC4S6NOh
      agent_session_id: null
    codebuild:
      project_name: bedrock-agentcore-github_slack_assistant-builder
      execution_role: arn:aws:iam::605664253368:role/AmazonBedrockAgentCoreSDKCodeBuild-us-west-2-97912bf415
      source_bucket: bedrock-agentcore-codebuild-sources-605664253368-us-west-2
    memory:
      mode: NO_MEMORY
      memory_id: null
      memory_arn: null
      memory_name: null
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    authorizer_configuration:
      customJWTAuthorizer:
        discoveryUrl: https://cognito-idp.us-west-2.amazonaws.com/us-west-2_x9N6oDWpA/.well-known/openid-configuration
        allowedClients:
          - 4s1367u2170qs9jb92qss1vfku
    request_header_configuration:
      allowedHeaders:
        - "Authorization"
    oauth_configuration: null
